// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6-E8t4sSZz4AZlqOL-99dsS2iE5Vr4rg',
    appId: '1:616016688484:web:64e4a560103c28a236b671',
    messagingSenderId: '616016688484',
    projectId: 'roadeye2',
    authDomain: 'roadeye2.firebaseapp.com',
    storageBucket: 'roadeye2.firebasestorage.app',
    measurementId: 'G-X124K8C3W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCn8-EF4PWswRm4kx7WKZq0GJ9LtuT6uk',
    appId: '1:616016688484:android:a8da57df27405b2536b671',
    messagingSenderId: '616016688484',
    projectId: 'roadeye2',
    storageBucket: 'roadeye2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKa2h4-LD-x916o4kPlunBJNPooEuxg6s',
    appId: '1:616016688484:ios:aadc394785bdcdea36b671',
    messagingSenderId: '616016688484',
    projectId: 'roadeye2',
    storageBucket: 'roadeye2.firebasestorage.app',
    iosBundleId: 'com.example.roadeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKa2h4-LD-x916o4kPlunBJNPooEuxg6s',
    appId: '1:616016688484:ios:aadc394785bdcdea36b671',
    messagingSenderId: '616016688484',
    projectId: 'roadeye2',
    storageBucket: 'roadeye2.firebasestorage.app',
    iosBundleId: 'com.example.roadeye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6-E8t4sSZz4AZlqOL-99dsS2iE5Vr4rg',
    appId: '1:616016688484:web:3de5a412761df53836b671',
    messagingSenderId: '616016688484',
    projectId: 'roadeye2',
    authDomain: 'roadeye2.firebaseapp.com',
    storageBucket: 'roadeye2.firebasestorage.app',
    measurementId: 'G-J9KZ1FFS42',
  );
}
